version: '3.2'

services:
  redis:
    container_name: redis_edu
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - localhost

  php:
    container_name: php_edu
    build: docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    hostname: localhost
    ports:
      - 9000:9000
    links:
      - redis
    networks:
      - localhost

  nginx:
    container_name: nginx_edu
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8990:8990
    links:
      - php
    networks:
      - localhost

  mysql:
    container_name: mysql_edu
    image: mysql:5.7.31
    volumes:
      - ./data/mysql:/data
    environment:
      - MYSQL_ROOT_PASSWORD=edu
      - MYSQL_DATABASE=edu
      - MYSQL_USER=edu
      - MYSQL_PASSWORD=edu
    networks:
      - localhost

  phpMyAdmin:
    container_name: myadmin_edu
    image: phpmyadmin/phpmyadmin:4.7.2-1
    ports:
      - 21800:80
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=edu
    networks:
      - localhost

  phpRedisAdmin:
    container_name: redisadmin_edu
    image: erikdubbelboer/phpredisadmin:v1.11.0
    ports:
      - 21900:80
    links:
      - redis
    environment:
      - REDIS_1_HOST=redis
    networks:
      - localhost

networks:
  localhost: